/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TrendsRouteImport } from './routes/{-$locale}/trends'
import { Route as Char123LocaleChar125SourcesRouteImport } from './routes/{-$locale}/sources'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125EventsRouteImport } from './routes/{-$locale}/events'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as Char123LocaleChar125TrendsIndexRouteImport } from './routes/{-$locale}/trends.index'
import { Route as Char123LocaleChar125TrendsTopicRouteImport } from './routes/{-$locale}/trends.$topic'
import { Route as Char123LocaleChar125SkillsOpentrendsRouteImport } from './routes/{-$locale}/skills.opentrends'
import { Route as Char123LocaleChar125EventsFlowRouteImport } from './routes/{-$locale}/events_.flow'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TrendsRoute =
  Char123LocaleChar125TrendsRouteImport.update({
    id: '/{-$locale}/trends',
    path: '/{-$locale}/trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SourcesRoute =
  Char123LocaleChar125SourcesRouteImport.update({
    id: '/{-$locale}/sources',
    path: '/{-$locale}/sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/{-$locale}/login',
    path: '/{-$locale}/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125EventsRoute =
  Char123LocaleChar125EventsRouteImport.update({
    id: '/{-$locale}/events',
    path: '/{-$locale}/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125TrendsIndexRoute =
  Char123LocaleChar125TrendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125TrendsRoute,
  } as any)
const Char123LocaleChar125TrendsTopicRoute =
  Char123LocaleChar125TrendsTopicRouteImport.update({
    id: '/$topic',
    path: '/$topic',
    getParentRoute: () => Char123LocaleChar125TrendsRoute,
  } as any)
const Char123LocaleChar125SkillsOpentrendsRoute =
  Char123LocaleChar125SkillsOpentrendsRouteImport.update({
    id: '/{-$locale}/skills/opentrends',
    path: '/{-$locale}/skills/opentrends',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125EventsFlowRoute =
  Char123LocaleChar125EventsFlowRouteImport.update({
    id: '/{-$locale}/events_/flow',
    path: '/{-$locale}/events/flow',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/events': typeof Char123LocaleChar125EventsRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}/trends': typeof Char123LocaleChar125TrendsRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/events/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/trends/$topic': typeof Char123LocaleChar125TrendsTopicRoute
  '/{-$locale}/trends/': typeof Char123LocaleChar125TrendsIndexRoute
}
export interface FileRoutesByTo {
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/events': typeof Char123LocaleChar125EventsRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/events/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/trends/$topic': typeof Char123LocaleChar125TrendsTopicRoute
  '/{-$locale}/trends': typeof Char123LocaleChar125TrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/events': typeof Char123LocaleChar125EventsRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}/trends': typeof Char123LocaleChar125TrendsRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/events_/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/trends/$topic': typeof Char123LocaleChar125TrendsTopicRoute
  '/{-$locale}/trends/': typeof Char123LocaleChar125TrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/.well-known/api-catalog'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/events'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}/trends'
    | '/{-$locale}/'
    | '/{-$locale}/events/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/trends/$topic'
    | '/{-$locale}/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/.well-known/api-catalog'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/events'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}'
    | '/{-$locale}/events/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/trends/$topic'
    | '/{-$locale}/trends'
  id:
    | '__root__'
    | '/.well-known/api-catalog'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/events'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}/trends'
    | '/{-$locale}/'
    | '/{-$locale}/events_/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/trends/$topic'
    | '/{-$locale}/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125EventsRoute: typeof Char123LocaleChar125EventsRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125SourcesRoute: typeof Char123LocaleChar125SourcesRoute
  Char123LocaleChar125TrendsRoute: typeof Char123LocaleChar125TrendsRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125EventsFlowRoute: typeof Char123LocaleChar125EventsFlowRoute
  Char123LocaleChar125SkillsOpentrendsRoute: typeof Char123LocaleChar125SkillsOpentrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/trends': {
      id: '/{-$locale}/trends'
      path: '/{-$locale}/trends'
      fullPath: '/{-$locale}/trends'
      preLoaderRoute: typeof Char123LocaleChar125TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sources': {
      id: '/{-$locale}/sources'
      path: '/{-$locale}/sources'
      fullPath: '/{-$locale}/sources'
      preLoaderRoute: typeof Char123LocaleChar125SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/{-$locale}/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/events': {
      id: '/{-$locale}/events'
      path: '/{-$locale}/events'
      fullPath: '/{-$locale}/events'
      preLoaderRoute: typeof Char123LocaleChar125EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/trends/': {
      id: '/{-$locale}/trends/'
      path: '/'
      fullPath: '/{-$locale}/trends/'
      preLoaderRoute: typeof Char123LocaleChar125TrendsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125TrendsRoute
    }
    '/{-$locale}/trends/$topic': {
      id: '/{-$locale}/trends/$topic'
      path: '/$topic'
      fullPath: '/{-$locale}/trends/$topic'
      preLoaderRoute: typeof Char123LocaleChar125TrendsTopicRouteImport
      parentRoute: typeof Char123LocaleChar125TrendsRoute
    }
    '/{-$locale}/skills/opentrends': {
      id: '/{-$locale}/skills/opentrends'
      path: '/{-$locale}/skills/opentrends'
      fullPath: '/{-$locale}/skills/opentrends'
      preLoaderRoute: typeof Char123LocaleChar125SkillsOpentrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/events_/flow': {
      id: '/{-$locale}/events_/flow'
      path: '/{-$locale}/events/flow'
      fullPath: '/{-$locale}/events/flow'
      preLoaderRoute: typeof Char123LocaleChar125EventsFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125TrendsRouteChildren {
  Char123LocaleChar125TrendsTopicRoute: typeof Char123LocaleChar125TrendsTopicRoute
  Char123LocaleChar125TrendsIndexRoute: typeof Char123LocaleChar125TrendsIndexRoute
}

const Char123LocaleChar125TrendsRouteChildren: Char123LocaleChar125TrendsRouteChildren =
  {
    Char123LocaleChar125TrendsTopicRoute: Char123LocaleChar125TrendsTopicRoute,
    Char123LocaleChar125TrendsIndexRoute: Char123LocaleChar125TrendsIndexRoute,
  }

const Char123LocaleChar125TrendsRouteWithChildren =
  Char123LocaleChar125TrendsRoute._addFileChildren(
    Char123LocaleChar125TrendsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125EventsRoute: Char123LocaleChar125EventsRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125SourcesRoute: Char123LocaleChar125SourcesRoute,
  Char123LocaleChar125TrendsRoute: Char123LocaleChar125TrendsRouteWithChildren,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125EventsFlowRoute: Char123LocaleChar125EventsFlowRoute,
  Char123LocaleChar125SkillsOpentrendsRoute:
    Char123LocaleChar125SkillsOpentrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
